- go.mod
- go.sum
- types/block.go
closes: #16 
This PR aims to align the current core data types, Block and Header, with what we have in the spec with the constraint that we agreed not to tackle [immediate execution](#3) immediately (no pun intended). Further, I've limited this to all changes that do not change *any* other parts besides that (e.g. I did not move evidence over to `Block.Data` as this will make this less contained and more difficult to review). Also I didn't change any hashing hashing logic s.t. none of the current tests break. Both these constraints will be addressed in separate smaller PRs.
> Update core data types 

- .circleci/config.yml
- scripts/release_management/zip-file.py
Remove not required jobs and fix paths in circlci config. We can probably remove a few more later (or switch to github actions step by step).
> CI: Remove obsolete jobs and fix config

- consensus/types/round_state_test.go
- types/block.go
- types/test_util.go
Followup PR for #16 / #17:
- use `HexBytes` instead of `[]byte` for hashes
- move Evidence to Data to guarantee its availability
Note that preferably we would introduce a hash type (see https://github.com/LazyLedger/lazyledger-core/pull/17#discussion_r410491475). Here we only consistently use the data type that is used in other places for this purpose.
After this PR gets merged, I'll start with adding in the `RSMT2D` for computing roots.
> Data availability for evidence

- CHANGELOG_PENDING.md
- types/block.go
I'm not 100% certain this needs to be changed, so please disregard if not.
Fixes a typo causing an incorrect root hash of the data availability header by iterating over the column roots along with the row roots, as opposed to iterating over the row roots twice.
> types: fixes typo causing the roots not be hashed

- .github/workflows/e2e-nightly.yml
Add slack webhook. See https://github.com/rtCamp/action-slack-notify
Closes: #99
> Add slack web-hook to be notified about e2e tests

- crypto/secp256k1/secp256k1.go
- wrap the key in []Byte() to avoid overflow.
- fixes e2e failure
This is already in Tendermint just hasn't been added to LL
> crypto/secp256k1: fix .String()

- go.mod
- go.sum
Either merging this and updating to the lastest ll-core@master (or using this branch), or a replace directive in the sdk's go.mod to enforce the corresponding grpc version will fix all failing tests in https://github.com/lazyledger/cosmos-sdk/issues/2
Closes: #XXX
> Downgrade grpc to match the sdk's version (v1.33.2)

- rpc/jsonrpc/client/http_json_client_test.go
- test/e2e/generator/generate.go
- test/e2e/networks/ci.toml
- remove grpc as an abci protocol. 
- Remove the usage of v2 fast sync till bugs are fixed. 
Closes #148
> ci: fix nightly tests

- go.mod
- p2p/ipld/read.go
- p2p/ipld/read_test.go
Implementation for `GetLeafData`. 
Closes: 1/3 of #194
> Implement GetLeafData as described in ADR 002

- p2p/ipld/nmt_wrapper.go
- p2p/ipld/nmt_wrapper_test.go
- p2p/ipld/read.go
This PR was mostly taken from the [closed PR](https://github.com/lazyledger/nmt/pull/25) from nmt. As mentioned in the comments their, it makes more sense to keep the lazyledger-core login in lazyledger-core. This PR should be merged before for #235 and #232.
Closes: #237
> Implement rsmt tree wrapper for nmt

- go.mod
- go.sum
- p2p/ipld/nmt_wrapper.go
- p2p/ipld/nmt_wrapper_test.go
- p2p/ipld/plugin/go.mod
- p2p/ipld/plugin/go.sum
- p2p/ipld/plugin/nodes/nodes.go
- p2p/ipld/plugin/nodes/nodes_test.go
- p2p/ipld/read_test.go
- types/block.go
Update nmt to latest release v0.3.1
> update to nmt v0.3.1

- consensus/common_test.go
migling with these timeouts to see if that fixes the CI fails https://github.com/lazyledger/lazyledger-core/pull/241#issuecomment-813480110
> increase timeout threshold

- p2p/ipld/plugin/nodes/nodes.go
- types/block.go
As we compute the NMT tree for columns and rows of shares in an extended data square, we end up adding all the shares into IPFS two times, thus introducing unnecessary overhead, especially for IO. Considering how big blocks may become and how quickly they are generated, the overhead would scale significantly.
The PR introduces a simple patch in NMTNodeAdder to memoize added leaves not to be added a second time.
EDIT:
It also fixes incorrect use of `BatchAdder`
EDIT2:
Closes #204
> Prevent double writes of samples to IPFS

- consensus/state.go
- p2p/ipld/read_test.go
- types/block_test.go
During block proposal and testing, we are currently pinning data to IPFS by default. Pinning has significant overhead, so much so that it's causing the tests to timeout. This PR removes the default pinning option from block proposal and testing.|
Closes: #275
> Stop using the pinning option as a default

- go.mod
- go.sum
- p2p/ipld/nmt_wrapper_test.go
- p2p/ipld/plugin/nodes/nodes_test.go
- p2p/ipld/read.go
- p2p/ipld/read_test.go
- types/block.go
- types/block_test.go
- types/consts.go
- types/shares_test.go
add the constant `MinSquareSize` and make sure that empty blocks always have a square size equal to it.
Notably, I wasn't sure if the hash of an empty data availability header should always be that of a data availability header of an empty block, which is not empty, so this is not currently enforced.
Closes: #281
> enforce a minimum square size

- docs/lazy-adr/adr-002-ipld-da-sampling.md
This PR simply updates the APIs defined in ADR002 to match those that were implemented. This includes minor additions necessary for connecting to IPFS, selecting the codec for rsmt2d, and a different name for function to be ran after a leaf of data has been validated
Closes: #300
> update apis of adr002

- p2p/ipld/nmt_wrapper.go
- p2p/ipld/read_test.go
So I've finally managed to find the issue which caused RetrieveBlockData not to work in #293. The problem was in the wrong root calculation in wrapped NMT for empty blocks.
P.S. This was my first adventure through the whole rsmt2 stack and it took unexpectedly long to find out the problem is still somewhere in LL. Original symptoms were too confusing but was kind of fun 🍵
> Fix empty block retrieval

- p2p/ipld/nmt_wrapper.go
- types/consts.go
This PR only has minor doc additions to `ErasuredNamespacedMerkleTree` to appease this [comment](https://github.com/lazyledger/lazyledger-core/pull/299#discussion_r621177641)
Closes: #XXX
> minor nmt-wrapper doc addition

- p2p/ipld/sample.go
Originally Sample stored `src` field not to share `math/rand` object. After migration to `crypto/rand` that became redundant, though kept within the code, as previously unnoticed. The code also had the undesired side effects that caused `TestSampleSquare` to randomly fail. This PR fixes both issues.
> Remove redundant src field from Sample

- p2p/ipld/read.go
- p2p/ipld/read_test.go
- types/block.go
- types/block_test.go
This PR simply changes the way the number of tail padding shares are calculated in order to make squares with widths that are powers of two. However, this PR does not add any code that purposefully creates squares of a certain size. 
Closes: #257
> Use squares with a width that is a power of two

- config/config.go
- consensus/common_test.go
- consensus/state.go
- node/node.go
- p2p/ipld/race_detector_file.go
- p2p/ipld/racedetector/is_active.go
- p2p/ipld/racedetector/race_detector_file.go
- p2p/ipld/read_test.go
put the race detector file for the ipld/read_test.go in its own package. Locally, this doesn't make a difference, but the CI fails otherwise... still don't know why. 
Resorted to increasing the timeouts to make the consensus tests more reliable.
note: merging into #334, not master
Closes: #XXX
> Debugg CI for #334

- ipfs/defaults.go
- ipfs/init.go
- node/node.go
- node/node_test.go
- test/e2e/app/main.go
- test/e2e/runner/load.go
So I went through every field in IPFS config and set what suits FullNode the best with documentation for every single field. We should also create a setup for LightNode and configuration for it accordingly
NOTE: The PR also sets Badger as default datastore
> Define default configuration for embedded IPFS in FullNode

- docs/lazy-adr/adr-003-application-data-retrieval.md
Rendered: https://github.com/lazyledger/lazyledger-core/blob/ismail/adr003-appdata-retrieval/docs/lazy-adr/adr-003-application-data-retrieval.md
ref: #221
> adr: add API for retrieving data for a particular namespace only

- libs/db/badgerdb/db.go
- node/node.go
- node/node_test.go
- p2p/transport_test.go
- rpc/test/helpers.go
This PR:
- Uses an in-memory DB for unit tests (still badger though)
- increases some timeouts that help with test flakyness
- Skips a test that was a PITA (and is completely unrelated to the correctness of the consensus / LL or anything we are tying to do right now and in the next few months)
> node tests: Use in memory badger in unit tests

- crypto/merkle/hash.go
- crypto/merkle/proof.go
- crypto/merkle/proof_key_path_test.go
- crypto/merkle/proof_test.go
- crypto/merkle/tree.go
- go.mod
- go.sum
This PR makes some optimizations that produce the following results compared to the `master` implementation:
```
name                          old time/op    new time/op    delta
HashAlternatives/recursive-8    72.2µs ± 6%    65.0µs ± 1%   -9.94%  (p=0.000 n=10+10)
HashAlternatives/iterative-8    71.5µs ± 1%    65.6µs ± 1%   -8.26%  (p=0.000 n=8+8)
name                          old alloc/op   new alloc/op   delta
HashAlternatives/recursive-8    25.4kB ± 0%     6.5kB ± 0%  -74.45%  (p=0.000 n=10+10)
HashAlternatives/iterative-8    28.1kB ± 0%     9.2kB ± 0%  -67.33%  (p=0.000 n=10+10)
name                          old allocs/op  new allocs/op  delta
HashAlternatives/recursive-8       497 ± 0%       200 ± 0%  -59.76%  (p=0.000 n=10+10)
HashAlternatives/iterative-8       498 ± 0%       201 ± …
```
> crypto/merkle: hashing ~10% faster and ~60% fewer allocs

- consensus/byzantine_test.go
- consensus/common_test.go
- consensus/mempool_test.go
- consensus/reactor_test.go
- consensus/replay_file.go
- consensus/replay_test.go
- consensus/state.go
- consensus/state_test.go
- consensus/wal_test.go
- go.mod
- light/client.go
- node/node.go
- p2p/ipld/racedetector/is_active.go
- p2p/ipld/racedetector/race_detector_file.go
- p2p/ipld/read.go
- p2p/ipld/read_test.go
- p2p/ipld/validate.go
- p2p/ipld/validate_test.go
- p2p/ipld/write.go
- p2p/ipld/write_test.go
The PR's main goal is to facilitate everything related to IPFS usage by:
1. Using IPLD Merkle DAG interfaces instead of CoreAPI.
2. Reworking Data retrieval logic to be based solely on IPLD Dag(optimization)
3. Use of Dag Sessions(optimization)
4. Reworking and cleaning some tests
DAS timings before 2 above optimizations:
```
I[2021-05-23|23:12:11.531] Successfully finished DAS sampling           height=629 numSamples=15 elapsedtime=1.015415079s
I[2021-05-23|23:12:11.768] Starting Data Availability sampling          height=630 numSamples=15 squareWidth=16
I[2021-05-23|23:12:12.690] Successfully finished DAS sampling           height=630 numSamples=15 elapsedtime=921.977083ms
I[2021-05-23|23:12:13.060] Starting Data Availability sampling          height=631 numSamples=15 squareWidth=16 …
```
> Use IPLD Dag instead of CoreAPI

- cmd/tendermint/commands/light.go
- consensus/byzantine_test.go
- consensus/common_test.go
- consensus/reactor_test.go
- consensus/replay_file.go
- consensus/state.go
- consensus/wal_test.go
- go.mod
- ipfs/defaults.go
- ipfs/embedded.go
- ipfs/mock.go
- ipfs/provider.go
- node/node.go
- p2p/ipld/net_test.go
- p2p/ipld/read_test.go
- p2p/ipld/validate.go
- p2p/ipld/validate_test.go
- p2p/ipld/write.go
- p2p/ipld/write_test.go
> Note: those PR does not only manual providing but I chose the name for the biggest change. 
This PR: 
* Provides networking tests in IPLD. Probably closes #349, not sure if that's enough
* Makes light client serve IPFS API by default(should be changed later to be configurable)
* Disables Bitswap providing and [reproviding](https://github.com/lazyledger/lazyledger-core/issues/393).
* Extends PutBlock with logger and code to manually provide Row and Cols to DHT
* Introduces provider in p2p/ipld that handles point above. NOTE: We need to extract it into an independent singleton. We can do this along with https://github.com/lazyledger/lazyledger-core/issues/393, so the code for provider is not final.
* Starts using ContentRouting interface from libp2p in Node(gained from IpfsNode which is …
> ipld: Manual providing 

- consensus/state.go
See code comment of why this makes sense
> Small workaround to enable using the DAS light client again

- blockchain/v0/reactor.go
- blockchain/v0/reactor_test.go
- consensus/byzantine_test.go
- consensus/common_test.go
- consensus/mempool_test.go
- consensus/reactor_test.go
- consensus/replay.go
- consensus/replay_file.go
- consensus/replay_test.go
- consensus/state.go
- consensus/wal_test.go
- evidence/pool_test.go
- go.mod
- ipfs/mock.go
- node/node.go
- node/node_test.go
- rpc/core/blocks.go
- rpc/core/blocks_test.go
- rpc/core/tx.go
- state/services.go
- store/mock.go
- store/store.go
- store/store_test.go
This PR builds off of #372 and #356 to [save](https://github.com/lazyledger/lazyledger-core/blob/c2d117634cbe3dc97313068b58c79518b0bf1ef5/store/store.go#L325-L403) and [load](https://github.com/lazyledger/lazyledger-core/blob/c2d117634cbe3dc97313068b58c79518b0bf1ef5/store/store.go#L99-L123) block data via IPFS. It should be noted that it does not completely remove the [use of block parts or the `PartSetHeader`](https://github.com/lazyledger/lazyledger-core/blob/c2d117634cbe3dc97313068b58c79518b0bf1ef5/store/store.go#L346-L353). It should also be noted that it is not yet explicit or configurable in when it retrieves data from IPFS per the request of #373.
Closes: #373
> Save and load block data using IPFS

- p2p/ipld/wrapper/nmt_wrapper.go
- types/block.go
- types/block_test.go
- types/share_splitting.go
While wearing a debugging hat, confusing myself, and thinking about what went wrong and what could be done better, I found a better solution for https://github.com/celestiaorg/lazyledger-core/pull/299. Also, removed one allocation in a hot path(`wrapper.Push`).
Addition: use one global tail padded share instead of generating them everytime
> Update tail padded shares with NMT wrapper

- docs/lazy-adr/adr-003-application-data-retrieval.md
`RetrieveMessages` definition lacks `nid` parameter.
> Add namespace id to RetrieveMessages

- libs/autofile/group.go
This PR fixes a typo in a log message.
> libs/autofile: Fix typo in log message

- README.md
This PR removes the `Install` and `Quick Start` sections as the links are broken. I can make an issue to update the README with these instructions later.
> README: remove install + quick start sections as links are broken

- docs/lazy-adr/adr-005-decouple-blockid-and-partsetheader.md
This PR introduces a small ADR to document the decision to decouple the `PartSetHeader` from the `BlockID` and remove it where possible. As stated in the ADR, this design is not really an alternative to other more discussed designs, but more of a short term solution and a stepping stone to other better schemes.
[rendered](https://github.com/celestiaorg/lazyledger-core/blob/e22e3d74538c3c79b616e14eaa52e63f4f8f2fe8/docs/lazy-adr/adr-005-decouple-blockid-and-partsetheader.md)
> Document already made Decisions to Decouple Blockid and PartSetHeader in ADR 005

- ipfs/plugin/nmt_test.go
- testutils/blockdata.go
- types/block.go
- types/block_test.go
- types/shares_test.go
- types/tx.go
This PR exports the functions necessary to generate random block / share / message data. I'd like to reuse these functions for testing purposes outside the scope of the `types` package as it's a useful tool for mocking away celestia-core functionality. Eventually, we can expand this `testutils` package to also mock state and other data produced by a celestia core node.
**TODO**: 
Add generator in `testutils` for DAH, and Header based on block data
> types: export dummy random block generation functions

- consensus/state.go
> Revert writing to IPLD during defaultDecideProposal

- abci/example/dummyapp/main.go
This PR fixes a problem with the dummy app where the app crashes due to missing `ipfs` directory. 
Error message: 
```
ERROR: failed to create node: no IPFS repo found in /root/.tendermint/ipfs.
please use flag: --ipfs-init
```
This flag does not exist in our version anymore, so it's best to explicitly create the directory. If the directory is already created, it will not error out.
> abci/example/dummyapp: initialise the IPFS directory before starting dummy node

- docs/adr/adr-006-row-propagation.md
[Rendered](https://github.com/celestiaorg/lazyledger-core/blob/hlib/row-propagation-adr/docs/lazy-adr/adr-006-row-propagation.md)
> ADR 006: Block Propagation with Rows

- abci/server/grpc_server.go
- abci/server/server.go
- abci/server/socket_server.go
- config/config.go
- config/toml.go
we need to restore some unused code to get the cosmos-sdk to compile. This should be reevaluated after we update to the latest versions of tendermint and the sdk.
Closes: #521
> Add unused code back in to preserve compatibility with the sdk

- types/block.go
- types/shares_test.go
This quick patch fixes the bug @renaynay found by sorting messages before they are split. This will allow for messages to not be sorted before calling the `SplitIntoShares` method on `Messages`, and protects against accidental panics.
Closes: #545
> sort namespaced shares before splitting

- docs/celestia-architecture/adr-005-decouple-blockid-and-partsetheader.md
- docs/celestia-architecture/adr-006-row-propoagation.md
- docs/celestia-architecture/adr-007-minimal-changes-to-tendermint.md
I thought these were added back into #534, but were lost while fixing the git history.
> add in missed celstia ADRs

- types/share_merging.go
export parsing functions in order to use them in dalc. While we only currently need `ParseMsgs`, eventually I think we will need the others for fraud proofs in celestia-node, so I went ahead and exported them as well.
Closes: #578
> export parsing msgs 34.x

- types/tx.go
- types/tx_test.go
I didn't know protobuf doesn't check types when unmarshalling, so there needs to be some check to prevent random stuff from being returned successfully from `DecodeChildTx`
> protobuf decode tx patch

- .github/workflows/linter.yml
- docs/architecture/README.md
This adds a check to the linter workflow to check that all ADRs are linked in `docs/architecture/README.md`. This was considerably easier to implement thanks to the bash-foo @adlerjohn left in this [comment](https://github.com/celestiaorg/celestia-core/pull/401#pullrequestreview-679543923) ❤️.
Closes: https://github.com/celestiaorg/celestia-core/issues/404
1. Added this check and observed errors in [this workflow](https://github.com/rootulp/celestia-core/runs/5635887445?check_suite_focus=true)
2. Added links to those ADRs, now check passes
> Add ADRs README check to linter

- .github/workflows/lint.yaml
the linter auto updates to the latest version of go, which breaks our linter.
Closes: #XXX
> force linter to use go 1.17

- .github/workflows/docker.yml
The `Build & Push` workflow was failing on the default branch (https://github.com/celestiaorg/celestia-core/actions/runs/2149689908) since obviously we can't push to Tendermint's repo. Removes the login and push steps, but keeps build.
> Remove push from Build & Push ci

- .github/workflows/tests.yml
- abci/client/socket_client.go
- abci/server/socket_server.go
The app_tests, which uses the tendermint socket client, is failing. After spending quite a bit of time debugging, it appears that the socket client always returns `nil` when the socket server calls `ProcessProposal`. This doesn't appear on the other integration tests (grpc and in process). One of the reasons why this was occurring was because we were missing handlers for `ProcessProposal` requests/responses, which have been added. Rather than continuing to debug, this PR is suggesting that we disable this test until we update to v0.36.x, in which it should be fixed, and also because we will not be making use of the socket client.
I will continue to debug this test, unless we decide to merge this PR. If we do end up merging, we should **not** cherry pick this PR on to v0.36.x when we …
> Temporarily disable socket client app test

- internal/evidence/pool_test.go
- internal/state/execution.go
- internal/state/helpers_test.go
- internal/state/state.go
- internal/state/test/factory/block.go
- internal/state/validation_test.go
- proto/tendermint/blocksync/message_test.go
- types/block.go
- types/block_test.go
- types/event_bus_test.go
- types/test_util.go
this PR passes the entire block data instead of the txs, evidence, and messages as distinct objects. This then passes along crucial information such as the square size and the data hash.
blocking https://github.com/celestiaorg/celestia-app/pull/419
Closes #753
> pass the entire block data when making a block

- .github/workflows/docker.yml
Modified Build Docker CI to only run when pushing to default branches. No longer running for PRs.
Closes: #717
> run docker ci only for pushes to default branch

- .github/dependabot.yml
Fixes #697
Not actually 100% sure the `dependency-name` field is set correctly, but I guess we'll find out.
> Configure dependabot to only check for Celestia deps.

- pkg/da/data_availability_header.go
The spec does list `rowRoots` and `colRoots` as separate fields: https://github.com/celestiaorg/celestia-specs/blob/master/src/specs/data_structures.md#availabledataheader
> Fix comment on rowRoots and colRoots

- README.md
Replace the current Tendermint README with a Celestia specific README (sourced from `v0.35.x-celestia` branch)
> Use Celestia specific README

- light/proxy/routes.go
- light/rpc/client.go
- rpc/client/http/http.go
- rpc/client/interface.go
- rpc/client/local/local.go
- rpc/client/mock/client.go
- rpc/client/rpc_test.go
- rpc/core/blocks.go
- rpc/core/blocks_test.go
- rpc/core/routes.go
Changes the `query` to `begin`/`end` when creating a data root over a set of blocks.
Closes https://github.com/celestiaorg/celestia-core/issues/837 https://github.com/celestiaorg/celestia-app/issues/604
> Use begin end/block instead of query in data commitments

- .github/workflows/lint.yml
Closes https://github.com/celestiaorg/celestia-core/issues/821
This key isn't present in https://github.com/tendermint/tendermint/blob/v0.34.21/.github/workflows/lint.yml#L27-L31
> Fix golangci config warning

- types/block.go
This TODO appears resolved because a dedicated type (`namespace.ID`) is used instead of `[]byte`
> docs: remove resolved TODO

- proto/tendermint/types/types.pb.go
- types/block.go
- types/block_test.go
Partially addresses https://github.com/celestiaorg/celestia-core/issues/887 by removing two exported methods which are no longer needed after this refactor: https://github.com/celestiaorg/celestia-core/pull/879#discussion_r1019587387 and addressing this feedback: https://github.com/celestiaorg/celestia-core/pull/879#discussion_r1019596230
After this change, celestia-app can sort a slice of blobs via:
```golang
sort.Sort(coretypes.BlobsByNamespace(data.Blobs))
```
and verify a slice of blobs is sorted via:
```golang
if sort.IsSorted(coretypes.BlobsByNamespace(data.Blobs)) {
// ...
}
```
> chore: clarify sort for blobs

- proto/tendermint/types/types.pb.go
- types/block.go
Addresses this feedback https://github.com/celestiaorg/celestia-core/pull/879/files#r1020196368
> fix: comment for blobs

- mempool/mempool.go
Originally reported in https://github.com/celestiaorg/celestia-core/pull/898#discussion_r1046379044
Note that this comment is the only difference between celestia-core v0.34.x-celestia and tendermint v0.34.20: https://www.diffchecker.com/dmlnxenh so it seems residual
> chore: remove residual comment

- CHANGELOG_PENDING.md
- consensus/reactor.go
Cherry picks William's commit fixing the precommit tallying logic
Ref: tendermint/tendermint/pull/9760
> consensus: correctly save reference to previous height precommits (backport #9760) (#9776)

- .github/workflows/check-generated.yml
Disabled mock checks because they were manually modified in v0.34.23 to adhere to the new Peer interface.
This should be resolved in v0.37.x and we can reactivate this then. 
Ref: https://github.com/celestiaorg/celestia-core/pull/906#issuecomment-1348036502
> disable generated mocks check

- docs/celestia-architecture/adr-002-ipld-da-sampling.md
Fixes the rsmt2d link in ADR-002 to point correctly to the rsmt2d GitHub repository
> chore: Fix link to the rsmt2d library repo

- blockchain/v0/reactor.go
Closes: #926
This is a possible solution to the problem outlined in the issue where the integrity of the `Data` struct which is relied upon by the application isn't checked at all in blocksync. 
I have looked into ways of testing this but this is ridiculously hard (even going across multiple repos). The best solution I can think of is to refactor the blocksync v0 to use interfaces for the `BlockExecutor` so I am able to hook up a mock to check that the methods are called.
> blocksync: run process proposal when verifying new blocks

- config/config.go
- config/config_test.go
- config/toml.go
These have been deprecated and are removed in v0.37. This PR disables them for now so I don't have to update them as well with #929
> blocksync: disable v1 and v2 reactors

- go.mod
- go.sum
- rpc/core/blocks.go
- rpc/core/blocks_test.go
Fixes the data commitments from only committing to data roots to also include the heights
Closes: https://github.com/celestiaorg/celestia-core/issues/932
> fix: create commitments to data root tuples instead of just data roots

- go.mod
- go.sum
- rpc/core/blocks.go
- Remove dependency on geth dependency for encoding the data root
- Manually pad the hex representation of the height to 32 bytes and concatenate the data root to it.
Closes: #934
> QGB remove dependency on geth dependency for encoding the data root

- rpc/client/rpc_test.go
- rpc/core/blocks.go
- rpc/core/blocks_test.go
Related to https://github.com/celestiaorg/celestia-app/issues/1513
be advised that it may take some time before it …
> fix: add an extra check when the data commitment first block is 0

- state/execution.go
- state/execution_test.go
- types/events.go
In PR #940, a SignedBlockEvent was introduced which would be consumed by bridge nodes whenever a consensus node committed a block. The event joins the blocks header and data fields with the seen commit and validator set. However the validator set that was being sent was not at height h of the header, but height h + 1. Hence when there were validator set changes, bridge nodes reported a validator hash mismatch. This was because `state.Validators` had already been updated to the following height. To fix this, we use `state.LastValidators` instead.  
---
> fix: send LastValidators instead of Validators in SignedBlock event

- rpc/core/blocks.go
be advised that it may take some time before it is merged - especially if it has
not yet been discussed with the …
> chore: remove unused `heightsByQuery` function

- types/events.go
registers the new event with the json lib. This fixes the bug where websocket subscriptions to EventDataSignedBlock fail but don't error.
> fix: register EventDataSignedBlock in tendermint's json lib

- rpc/core/env.go
we missed a typo/bug in [#869](https://github.com/celestiaorg/celestia-core/pull/869/commits/c569855a3e10b8f93512b6b1ef6c0c845f920bfe) :sweat_smile: , which causes the node to lock during start for networks with large genesises. Personally I'm still of the opinion that those mutexes should be removed entirely since afaiu they don't help if we're we're running multiple in process nodes, but we can do that in a different PR
> fix: stop locking mid loop for large genesis files

- rpc/core/blocks.go
Closes https://github.com/celestiaorg/celestia-core/issues/1019
Question: Are we using [`unclog`](https://github.com/informalsystems/unclog) for changelogs in this repo for every PR? or no need?
> feat: rely on the block store solely to generate QGB commitments

- consensus/replay.go
- consensus/replay_file.go
- consensus/replay_test.go
- node/node.go
> feat: pass software version from abci to node info

- node/node.go
This PR adds the software version, provided in the `Info` ABCI call by the application as an additional label posted by all Prometheus metrics/
> feat: include software version as a label in all metrics

- rpc/core/blocks.go
- rpc/core/blocks_test.go
Closes https://github.com/celestiaorg/celestia-core/issues/1040
After merging this one, I will cherry-pick this change for main. Then, I will open a separate PR for main to remove the square size and the data hash from the `Data` struct.
---
> feat: remove square size from qgb commitment creation

- rpc/core/blocks.go
- rpc/core/blocks_test.go
Fixes https://github.com/celestiaorg/orchestrator-relayer/issues/432
> fix: end exclusive data commitment range fix

- rpc/core/blocks.go
- rpc/core/blocks_test.go
Cherry pick https://github.com/celestiaorg/celestia-core/pull/1058 to main
---------
be advised that it may take …
> fix: end exclusive data commitment range fix (#1058)

- consensus/state.go
- pkg/trace/schema/consensus.go
To accurately gauge block time, it's essential to track the timestamps of committed blocks. The modifications made in this PR incorporate this feature.
Incremental work toward https://github.com/celestiaorg/celestia-core/issues/1056
> feat: traces block height and timestamp for InfluxDB

- mempool/v1/reactor.go
This PR records that we have sent the peer the transaction to avoid doing it a second time
> feat: mempool v1 records which peer it has sent the tx

- p2p/metrics.go
- p2p/peer.go
Inline with https://github.com/celestiaorg/celestia-core/issues/1077
Our past experimentation showed that none of the current Prometheus traffic related metrics encompass all the information regarding the message type, peer ID and channel ID. This deficiency can be addressed by incorporating peer IDs for `message_receive_bytes_total` and `message_send_bytes_total`.  This PR provides this feature.
I tested it by executing a local validator node and examining the Prometheus metrics endpoint. Here's an example of the output:
```
cometbft_p2p_message_send_bytes_total{chID="0x40", chain_id="mocha-4", message_type="blockchain_StatusResponse", peer_id="cb7adca6fbaabc5336c5eebbc1312390a2bb9d2d", version="1.0.0-rc0-278-g4c452c5f4"} 8
```
> feat: includes peer_id as a label in the MessageSendBytesTotal and MessageReceiveBytesTotal Prometheus metrics

- types/block.go
Found in celestia-node header validation check. If a malformed `ExtendedHeader` with a nil Commit is broadcasted through the network, it would cause recipients to panic. We decided the check belongs in core as ValidatorSet also does a nil check.
> fix(types): Implement nil check on commit.ValidateBasic 

- consensus/metrics.go
- consensus/state.go
- test/maverick/consensus/state.go
Closes https://github.com/celestiaorg/celestia-core/issues/1077
I have verified the outcome of this pull request, and the block time gauge now correctly appears in the Prometheus endpoint:
```
cometbft_consensus_block_time_seconds{chain_id="mocha-4",version="1.0.0-rc16"} 11.623671263
```
> feat: tracks block time using a Prometheus gauge metric type

- mempool/cat/reactor.go
- mempool/cat/reactor_test.go
> chore: refactors CAT mempool to use SendEnvelope instead of Send

- mempool/v1/mempool.go
- mempool/v1/reactor.go
This PR refactors the mempool implementation to ensure consistent use of the `Lock` and `Unlock` methods for mutex management, promoting code reusability and traceability.
> chore: ensures consistent use of Lock and Unlock to acquire write-lock on the mempool v1

- mempool/cat/pool.go
- mempool/cat/pool_test.go
- mempool/v1/mempool.go
- mempool/v1/mempool_test.go
This modifies the behavior of the `ReapMaxBytesMaxGas` method called by consensus. Prior we would return the tx set the moment the first tx was greater than the limit. Now instead of breaking we continue through all txs. This means that a large tx doesn't block smaller less priority transactions from getting through.
> feat: loop through all txs before returning the tx set to consensus

- config/config.go
- p2p/conn/connection.go
There are two default SendRate/RecvRate settings in the codebase:
- The first one is a constant defined in the `connection.go` file, which is set to 512KB/s. You can find it in the code at this [link](https://github.com/celestiaorg/celestia-core/blob/main/p2p/conn/connection.go#L43).
- The second default value is set in the `config.go` file, which configures various P2P settings. Among these configurations, the SendRate and RecvRate default to 5MB/s. You can locate this in the code at this [link](https://github.com/celestiaorg/celestia-core/blob/main/config/config.go#L609).
When a node is running, the SendRate and RecvRate values that take effect are the ones specified in the `config.go` file, which is 5MB/s.
This PR aims to consolidate these two scattered default values. By doing so, it …
> chore: Consolidating default SendRate and RecvRate settings for clarity and consistency

- .github/workflows/check-generated.yml
- .github/workflows/coverage.yml
- .github/workflows/e2e-manual.yml
- .github/workflows/e2e-nightly-34x.yml
- .github/workflows/e2e.yml
- .github/workflows/fuzz-nightly.yml
- .github/workflows/govulncheck.yml
- .github/workflows/lint.yml
- .github/workflows/pre-release.yml
- .github/workflows/release-version.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- DOCKER/Dockerfile
- README.md
- go.mod
- go.sum
- scripts/proto-gen.sh
- test/docker/Dockerfile
- test/e2e/docker/Dockerfile
Closes https://github.com/celestiaorg/celestia-core/issues/1123
Unblocks https://github.com/celestiaorg/celestia-core/issues/1023
We may consider deleting everything in `docs/*` with the exception of `docs/celestia-architecture` so we don't need to maintain it.
> build(deps): upgrade to Go 1.21.3

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/proposal.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/issue_template.md
Some revisions were needed in the Github PR and issue templates to update links and wording, ensuring they refer to the celestia-core repository instead of cometbft.
> chore: updates PR and issue templates to properly reference celestia-core

- config/config.go
- config/toml.go
- node/tracing.go
- pkg/trace/client.go
- pkg/trace/schema/tables.go
- test/e2e/pkg/infrastructure.go
- test/e2e/pkg/testnet.go
There's an viper property or potential bug that stops us from overriding the default values for slices of strings. The "solution" atm is to use a string and parse it later like animals later. Unfortunately I think this is breaking since we're changing what a config is doing so tbh I'm not sure if we can ever include this in v1. If that's the case then we might want to consider not merging this to v0.34.x-celestia and only to main.
closes #1141
> fix!: change the instrumentation config to circumvent viper bug

- spec/light-client/verification/Blockchain_A_1.tla
- spec/light-client/verification/verification_001_published.md
- spec/light-client/verification/verification_002_draft.md
- spec/light-client/verification/verification_003_draft.md
> chore(spec/light-client/verification): typo fix

- README.md
For new contributors like me,it would be more useful to see a GitPOAP explanation in the README.
This file is the same as my pull request here:https://github.com/celestiaorg/celestia-core/pull/1156
It might be helpful for beginners to include this in the READM.
close https://github.com/celestiaorg/celestia-core/issues/1155
> docs: add GitPOAP section to README

- mempool/metrics.go
- mempool/v1/mempool.go
- node/node.go
- pkg/trace/schema/mempool.go
This PR introduces more precise mempool metrics to provide a clearer view in why txs are getting evicted or failing
> feat: more precise mempool metrics

- docs/app-dev/getting-started.md
original link is broken:
-->
---
> docs: fix link to install.md

- rpc/core/mempool.go
Closes https://github.com/celestiaorg/celestia-core/issues/1168
> feat: export `ErrTimedOutWaitingForTx`

- mempool/cat/pool_test.go
- mempool/v1/mempool_test.go
This test is currently hyper flakey because it doesn't calculate priorities consistently due to the txs being different sizes.
closes #1132
> fix: make priority calculations consistent for TestTxMempool_ReapMaxBytes

- libs/log/testing_logger.go
- p2p/conn/connection.go
- p2p/conn/connection_test.go
A PR towards #1162 
This PR introduces a comprehensive benchmark suite for MConnection, aimed at pinpointing performance bottlenecks. The tests evaluate the following aspects:
- Evaluating send queue capacity impact on the message transmission delay
- Assessing whether MConnection can fully utilize its maximum bandwidth 
- Testing performance beyond available bandwidth i.e., send and receive rates. This is to determine how the system behaves when message rates surpass the available bandwidth.
So far, no significant bottlenecks have been identified. In a follow-up PR, I plan to adjust additional parameters and will share the results and insights gained from these tests.
> test: MConnection benchmark

- types/protobuf.go
closes #1201 this issue only affects v0.34.x
> fix: pass version when converting between proto consensus params types

- consensus/reactor.go
- pkg/trace/schema/consensus.go
- pkg/trace/schema/tables.go
Closes #1200
This is deemed a breaking change because it modifies the signature of the `PickSendVote` public method within the `PeerState` type.
> feat!: traces gossiped votes in the InfluxDB 

- go.mod
This PR does not change any of the dependency, it only reorders the go.mod file into a direct and undirect import section, as go versions do since 1.17.
The reason your go.mod file got so many require sections is because during the 1.16 to 1.17 go.mod styling transition you had different contributors updating the go.mod file with pre 1.17 and post 1.17 releases of go.
See https://go.dev/doc/modules/gomod-ref:
> At go 1.17 or higher:
section for a description of what changed.
> chore: cleanup go.mod file require sections

- mempool/cat/cache.go
- mempool/cat/cache_test.go
- mempool/cat/reactor.go
- mempool/cat/reactor_test.go
- mempool/cat/requests.go
> fix: correctly prune peers from the seenTxSet when disconnecting

- mempool/cat/pool.go
- mempool/metrics.go
- mempool/v0/clist_mempool.go
- mempool/v1/mempool.go
This PR exposes a new metric SizeBytes for the total size of the mempool in bytes. We already keep track of this value internally, in the variable txsBytes. Currently there is the metric Size for the size of the mempool in number of transactions.
> feat(mempool): add metric size of pool in bytes

- consensus/metrics.go
- consensus/state.go
This adds two counters to the consensus metrics:
- ApplicationRejectedProposals
- TimedOutProposals
It also adds a third `StartHeight` which is set once upon start so we know how many heights the metrics have been running for
---
> feat: add more consensus metrics on rejected proposals

- consensus/replay.go
- state/state.go
- state/state_test.go
> fix: use genesis file app version  if it is set

- .github/workflows/check-generated.yml
- .github/workflows/coverage.yml
- .github/workflows/e2e-manual.yml
- .github/workflows/e2e-nightly-34x.yml
- .github/workflows/e2e.yml
- .github/workflows/fuzz-nightly.yml
- .github/workflows/govulncheck.yml
- .github/workflows/pre-release.yml
- .github/workflows/release-version.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- DOCKER/Dockerfile
- README.md
- go.mod
- scripts/proto-gen.sh
- test/docker/Dockerfile
- test/e2e/docker/Dockerfile
In order to fix the go vulnerabilities that are fixed in the new patch:
```
Vulnerability #1: GO-2024-2610
Errors returned from JSON marshaling may break template escaping in
html/template
More info: https://pkg.go.dev/vuln/GO-2024-2610
Standard library
Found in: html/template@go1.22
Fixed in: html/template@go1.22.1
Example traces found:
#1: test/fuzz/rpc/jsonrpc/server/handler.go:30:15: server.Fuzz calls http.ServeMux.ServeHTTP, which eventually calls template.Template.Execute
#2: rpc/jsonrpc/server/http_server.go:256:15: server.maxBytesHandler.ServeHTTP calls http.HandlerFunc.ServeHTTP, which eventually calls template.Template.ExecuteTemplate
Vulnerability #2: GO-2024-2600
Incorrect forwarding of sensitive headers and cookies on HTTP redirect in
net/http
More info: …
```
> chore: updates to go1.22.1

- mempool/cat/store.go
- mempool/cat/store_test.go
This is an alternative to #1267 that solves the current problem with reserving transactions by using a separate lookup map as suggested by @rootulp.
> fix: use a separate lookup map for reserving txs

- go.mod
- go.sum
I think the aws dep bumped viper in the last tracing PR, and 1.18 has this issue https://github.com/spf13/viper/issues/1706.
~~we can do this or https://github.com/celestiaorg/cosmos-sdk/pull/389~~
main uses v1.13 of viper, but 1.15 is the lowest we can use without a replace statement on this branch
> fix: downgrade viper

- light/rpc/client.go
- rpc/client/http/http.go
- rpc/client/interface.go
- rpc/client/local/local.go
- rpc/core/tx.go
- rpc/core/types/responses.go
This PR wraps the `ShareProof` into a `ResultShareProof` in the API. However, It doesn't change the custom query response since it's internal data and there is no need to wrap it.
Closes https://github.com/celestiaorg/celestia-core/issues/1306
> feat!: wrap ShareProof in ResultShareProof

- pkg/trace/local_tracer.go
- pkg/trace/local_tracer_test.go
Introduced constants for the tracer push configuration environment variables to reduce errors when setting and reading these variables in the code, particularly in downstream repositories.
Manual backport of https://github.com/celestiaorg/celestia-core/pull/1324
> chore: introduces constants for tracer push configs environment variable names (manual backport #1324)

- pkg/trace/local_tracer.go
- pkg/trace/local_tracer_test.go
Introduced constants for the tracer push configuration environment variables to reduce errors when setting and reading these variables in the code, particularly in downstream repositories.
> chore: introduces constants for tracer push configs environment variable names

- config/config.go
- config/toml.go
- consensus/state.go
Closes https://github.com/celestiaorg/celestia-core/issues/1247
This PR adds a configuration flag to limit the WAL to only contain internal messages.
This is useful because, as perceived in experiments, external_messages_WAL_writes ~= number_of_validators * internal_messages_WAL_writes, it reduces significantly the number of writes on the WAL. This makes sense because, by default, the WAL contains: votes, block parts, proposals, etc, from all the peers. In the meantime what we really need is the validator's own messages, and especially signature, not to double sign (To be confirmed because I guess, unless there is some bug in the signing process or some weird uncommon issue, the signature should be the same for each round).
~The configuration is added as experimental and is turned off by …
> feat: support writing only internal messages to WAL

- mempool/cat/pool_test.go
> test(mempool/cat): fix flaky TestTxPool_BroadcastQueue

- rpc/openapi/openapi.yaml
Adds the prove shares endpoint to the openapi specs
> docs: add the prove shares endpoint to openapi specs

- pkg/consts/consts.go
- rpc/core/blocks.go
This is done to support 33 hours batches of attestations in the API without having to make a breaking change
> chore: increase the data commitment blocks limit in the API (Backport #1268)

- Makefile
> chore: extract buf version

- pkg/trace/buffered_file.go
- pkg/trace/fileserver.go
- pkg/trace/local_tracer.go
- pkg/trace/local_tracer_test.go
- pkg/trace/tracer.go
This PR backports the fix to the writing and reading of traced files. This enables them to get push correctly every time instead of occasionally get cut from the seek being set to the beginning of the file. 
it also changes the api by unexporting a function that doesn't need to be exported or included in the interface.
these changes are included in the upcoming #1295
> fix!: trace file seeking

- .github/workflows/check-generated.yml
- .github/workflows/coverage.yml
- .github/workflows/e2e-manual.yml
- .github/workflows/e2e-nightly-34x.yml
- .github/workflows/e2e.yml
- .github/workflows/fuzz-nightly.yml
- .github/workflows/govulncheck.yml
- .github/workflows/pre-release.yml
- .github/workflows/release-version.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- DOCKER/Dockerfile
- README.md
- go.mod
- scripts/proto-gen.sh
- test/docker/Dockerfile
- test/e2e/docker/Dockerfile
This together with #1379 close #1377
> chore: bumps go version to 1.22.4 in main

- pkg/trace/fileserver.go
This PR updates the `S3Download` implementation to allow specifying the names of the traced tables when downloading from an S3 bucket. This enhancement enables file filtering and reduces the amount of data downloaded. It is a desirable feature when interacting with the traced data of large network tests. If no table name is provided, then `S3Download` downloads all the traced tables.
> feat: enhances S3Download to filter by traced table names

- DOCKER/Dockerfile
- README.md
- go.mod
- scripts/proto-gen.sh
- test/docker/Dockerfile
- test/e2e/docker/Dockerfile
This together with https://github.com/celestiaorg/celestia-core/pull/1378 close https://github.com/celestiaorg/celestia-core/issues/1377
> chore: bumps go version to 1.22.4 in v0.34.x-celestia

- .github/mergify.yml
I just merged two PRs to v0.34.x-celestia that should probably be backported to `main` if we're still maintaining `main`.
> ci: add ability to backport to main

- pkg/trace/fileserver.go
- pkg/trace/local_tracer.go
As part of migrating to Knuu for the celestia-app e2e tests, I debugged the tracing feature which required adding log messages to verify that the tracer pull server is up and running. This PR includes those log messages, which previously lived in a custom branch and were not available to everyone.
Part of https://github.com/celestiaorg/celestia-app/issues/3557
> chore: adds logs for the state of the trace pull server

- state/execution.go
- state/metrics.go
Add counter to the block executor metrics :
- RejectedTransactions
Resolves #1241
Unblocks #1007
> feat: metric for counting rejected transactions

- state/execution.go
- state/metrics.go
Add counter to the block executor metrics :
- RejectedTransactions
Port of #1415
> feat: metric for counting rejected transactions (port #1415)

- cmd/cometbft/commands/root.go
- config/config.go
- config/config_test.go
- libs/log/filter.go
- libs/log/filter_test.go
- libs/log/logger.go
- libs/log/nop_logger.go
- libs/log/tm_logger.go
- libs/log/tm_logger_test.go
- libs/log/tracing_logger.go
Closes https://github.com/celestiaorg/celestia-app/issues/3736
This adds warn logs when state sync settings are set while `enable = false` as it may lead to unexpected behavior whereas Config is valid.
> feat: warn when state sync settings are set while `enable = false`

- Makefile
- spec/ivy-proofs/README.md
- test/e2e/runner/exec.go
attempts to fix some of the e2e failures by updating docker compose usage
> fix: e2e by updating docker-compose to docker compose

- .github/workflows/check-generated.yml
- .github/workflows/coverage.yml
- .github/workflows/e2e-manual.yml
- .github/workflows/e2e-nightly-34x.yml
- .github/workflows/e2e.yml
- .github/workflows/fuzz-nightly.yml
- .github/workflows/govulncheck.yml
- .github/workflows/pre-release.yml
- .github/workflows/release-version.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- DOCKER/Dockerfile
- README.md
- go.mod
- scripts/proto-gen.sh
- test/docker/Dockerfile
- test/e2e/docker/Dockerfile
To align with the [go version used in celestia-app main](https://github.com/celestiaorg/celestia-app/blob/13f30980ddd0c52bca17908a193dbb291eefb76a/go.mod#L3) branch.
> chore: updates go version to 1.22.6

- consensus/state.go
We're currently using `newStep` to indicate whether to write a new trace, however this actually doesn't track when the round and step change happens and thus misses certain steps (like NewRound). This PR fixes it
> fix: use updateRoundStep to track consensus state changes

- state/state.go
- state/state_test.go
Unblocks https://github.com/celestiaorg/celestia-app/pull/3843
> fix: mocha block sync

- go.mod
- go.sum
Based on suggestion here https://github.com/celestiaorg/celestia-app/pull/3849#discussion_r1750074556
On Go 1.23 I got such failures:
```
% make build
--> Updating go.mod
--> Updating go.mod in ./test/interchain
../../../go/pkg/mod/github.com/grafana/pyroscope-go/godeltaprof@v0.1.6/internal/pprof/delta_mutex.go:30:20: undefined: runtime_cyclesPerSecond
../../../go/pkg/mod/github.com/grafana/pyroscope-go/godeltaprof@v0.1.6/internal/pprof/proto.go:320:8: undefined: runtime_expandFinalInlineFrame
make: *** [build] Error 1
```
Due to recent change in Go 1.23 where Go team removed some internal things. Simple bump works fine.
> chore(go.mod): bump grafana/pyroscope-go deps

- mempool/cat/pool_test.go
Closes https://github.com/celestiaorg/celestia-core/issues/1383
```
$ go test ./... -run "TestTxPool_ConcurrentlyAddingTx" -count=1000
ok  	github.com/tendermint/tendermint/mempool/cat	0.402s
```
> fix: TestTxPool_ConcurrentlyAddingTx

- mempool/cat/pool_test.go
Attempts to close https://github.com/celestiaorg/celestia-core/issues/1194
It takes a while to run so I can't run it with a super high count. 
```
$ go test ./... -run "TestTxPool_ConcurrentTxs" -count=10
ok  	github.com/tendermint/tendermint/mempool/cat	30.391s
```
> refactor: TestTxPool_ConcurrentTxs

- buf.work.yaml
deletes buf.work.yaml for the buf CI in https://github.com/celestiaorg/celestia-core/pull/1510 to work
> chore: remove buf.work.yaml

- docs/celestia-architecture/adr-009-cat-pool.md
We forgot to move CAT ADR from main to v0.34.x when we initially ported things across.
> docs: add cat pool adr

- state/txindex/kv/kv.go
- state/txindex/kv/kv_test.go
Fixes [#1526](https://github.com/celestiaorg/celestia-core/issues/1526)
> fix: tx search only returning one tx

- docs/celestia-architecture/adr-002-ipld-da-sampling.md
Fix Typographical Errors in Function Descriptions
This pull request addresses and fixes critical typographical errors in the descriptions of several functions that affect code clarity and correctness.
1. **Typo in "contex.Context"**:
- In the descriptions of the following functions: `ValidateAvailability`, `RetrieveBlockData`, and `PutBlock`, the reference to **"contex.Context"** has been corrected to **"context.Context"**.
- **Importance**: This correction is crucial as the incorrect spelling could lead to confusion or misinterpretation of the intended type, especially for developers referencing or using these functions. Proper naming ensures clarity, adherence to Go standards, and minimizes potential errors or misunderstandings in documentation and code navigation. …
> Typo fix Update adr-002-ipld-da-sampling.md

- mempool/cat/spec.md
- pkg/trace/README.md
This PR introduces fixes for typos in documentation files:
1. **First Commit:**
- **File:** `spec.md`
- **Change:** Fixed the typo `transcation` to `transaction`.
- **Importance:** Ensures accuracy and clarity in describing transaction-related processes.
2. **Second Commit:**
- **File:** `README.md`
- **Change:** Fixed the typo `separate` to `separated`.
- **Importance:** Maintains consistency in terminology and avoids confusion in the explanation.
These changes improve documentation accuracy and clarity, which is essential for better understanding and avoiding potential misinterpretations by developers.
---
> Fix typos in documentation

- docs/celestia-architecture/adr-001-block-propagation.md
- docs/celestia-architecture/adr-006-row-propagation.md
- docs/celestia-architecture/adr-template.md
- spec/p2p/messages/pex.md
This PR addresses multiple typos and fixes article usage errors across several documentation files. The following changes were made:
- Replaced "an" with "a" where the following word does not start with a vowel sound (e.g., "a user" instead of "an user").
- Added hyphen to "above-mentioned" to maintain proper spelling.
- Fixed phrasing for consistency and clarity in multiple sections.
Files updated:
- `adr-001-block-propagation.md`
- `adr-006-row-propagation.md`
- `adr-template.md`
- `pex.md`
These changes aim to improve readability and correctness in the documentation.
> fix: typos and article usage in various documentation files

- config/toml.go
Closes https://github.com/celestiaorg/celestia-core/issues/1550
In celestia-app I replaced celestia-core with this repo. Then created a new config file and observed:
```toml
timeout_propose = "3.5s"
timeout_commit = "4.2s"
```
> chore: deprecate timeout_commit and timeout_propose config

- .github/auto_request_review.yml
- .github/workflows/pr-review-requester.yml
Closes https://github.com/celestiaorg/celestia-core/issues/1556
> chore: request reviews from all core/app engineers

- spec/abci/abci.md
- spec/abci/apps.md
- spec/consensus/evidence.md
- spec/consensus/proposer-based-timestamp/pbts-algorithm_001_draft.md
- spec/consensus/proposer-based-timestamp/pbts_001_draft.md
This PR fixes several typos in documentation files.
> fix: typos in documentation files

- docs/celestia-architecture/adr-002-ipld-da-sampling.md
**Description of changes**:  
Fixed an issue with the file path structure: the first link to the `message_block_layout.md` file in the `src/rationale` directory was not accessible because the file should be located directly in the `rationale` folder. The link has now been corrected to point to the proper file location.
> fix: link for message_block_layout.md

- mempool/cat/reactor_test.go
Closes #1131 
Relax the time constrain for testing the eventual expiring of transactions. 
> fix(mempool/cat): TestReactorEventuallyRemovesExpiredTransaction flaky test

- mempool/cat/spec.md
- spec/abci/apps.md
- spec/p2p/messages/state-sync.md
Corrected `recieved` to `received`
Corrected `reponse` to `response`
Corrected `succesfully` to `successfully` x3.
Corrected `reciever` to `receiver`
> chore: fix typos

- crypto/merkle/README.md
- mempool/cat/spec.md
- pkg/trace/schema/misc.go
- spec/abci/apps.md
- spec/consensus/consensus-paper/IEEEtran.cls
- spec/consensus/proposer-based-timestamp/tla/TendermintPBT_001_draft.tla
- spec/p2p/messages/state-sync.md
Fix typos, such as:
- Recieved -> Received
- Fullfils -> Fulfills
> docs: fix typos

- mempool/cat/pool_test.go
Closes #1207  
After a lot of trial and errors and some research, the rationale behind this change of flaky test is: 
Because the TTL is 5ms which is very short, we need to have a more precise pruning interval to ensure that the transactions are expired, so that the expired event is caught quickly enough, while the second batch of transactions are not expired to prevent flaky behaviors.
```go test -run TestTxPool_ExpiredTxs_Timestamp github.com/tendermint/tendermint/mempool/cat -mod=readonly -race -count 100```
I run this command 200 times and see no failing one, which is kind of reliable compare to failing rate of 15-20% of old implemetation 
---
> test: fix `TestTxPool_ExpiredTxs_Timestamp` flake

- mempool/cat/pool.go
- mempool/cat/store.go
- mempool/cat/store_test.go
- mempool/v1/mempool.go
This is residual of https://github.com/celestiaorg/celestia-core/pull/1553
The problem is now even more subtle. Because the mempool mutexes weren't over both CheckTx and the actual adding of the transaction to the mempool we occasionally hit a situation as follows:
- CheckTx a tx with nonce 2
- Before saving it to the store, collect all transactions and recheck tx. This excludes the last tx with nonce 2, thus the nonce in the state machine is still  1
- Save the tx to the pool
- New tx comes in with nonce 3. The application is at 1 so rejects it expecting the next to be 2.
This PR fixes this pattern, however this won't be watertight for the CAT pool until we can order both on gas fee (priority) and nonce.
> fix: mempool locking mechanism in v1 and cat

- rpc/grpc/api.go
Addresses this https://github.com/celestiaorg/celestia-core/pull/1513#discussion_r1915448205
> chore: remove unnecessary new import lines in grpc/api.go

- config/config.go
- config/toml.go
- spec/consensus/proposer-selection.md
- spec/light-client/README.md
- spec/p2p/config.md
- spec/p2p/v0.34/configuration.md
Fix quotation mark in .md and .go files.
> docs: fix quotation mark

- test/e2e/generator/generate.go
- test/fuzz/README.md
- Fix "fuzzier" to "fuzzer" in test/fuzz/README.md 
- Fix "typologoy" to "topology" in test/e2e/generator/generate.go
> fix: typos in API docs and test files

- consensus/propagation/catchup_test.go
- consensus/propagation/commitment.go
- consensus/propagation/commitment_state.go
- consensus/propagation/commitment_test.go
- consensus/propagation/handers.go
- consensus/propagation/have_wants.go
- consensus/propagation/peer_state.go
- consensus/propagation/peer_state_test.go
- consensus/propagation/reactor_test.go
- consensus/propagation/types/combined_partset.go
- consensus/propagation/types/types.go
- node/node.go
fixes the peer state so that it actually stores state and then utilizes the parity data to reconstruct the block
> feat!: reconstruct the block after 

- mempool/v1/mempool.go
- mempool/v1/mempool_test.go
Closes https://github.com/celestiaorg/celestia-app/issues/4379
I don't know if this fixes all the issues with the v1 mempool but it should fix the data race reported in the issue. We had to move the mempool lock earlier in `CheckTx` before this map look up
```go
txmp.txByKey[txKey]
```
```shell
$ go test ./mempool/v1 -race -run TestConcurrentCheckTxDataRace
==================
WARNING: DATA RACE
Write at 0x00c0005987e0 by goroutine 89:
$ go test ./mempool/v1 -race -run TestConcurrentCheckTxDataRace
ok  	github.com/tendermint/tendermint/mempool/v1	(cached)
```
> fix(mempool/v1): data race

- consensus/byzantine_test.go
- consensus/common_test.go
- consensus/propagation/commitment.go
- consensus/propagation/commitment_test.go
- consensus/propagation/mempool.go
- consensus/propagation/reactor.go
- consensus/propagation/reactor_test.go
- consensus/propagation/types/types.go
- consensus/propagation/types/unmarshalling.go
- consensus/propagation/types/unmarshalling_test.go
- consensus/reactor_test.go
- consensus/replay_file.go
- consensus/wal_generator.go
- node/node.go
- types/marshalling.go
Closes https://github.com/celestiaorg/celestia-core/issues/1661
> feat: support recovering parts from the mempool

- rpc/client/rpc_test.go
- rpc/core/mempool.go
- rpc/openapi/openapi.yaml
Instead of creating a new RPC method that returns all the unconfirmed mempool transactions, I used -1 as a special flag to do that. I think it's fine to do so. If it's not, can always define a new endpoint.
> feat: purpose -1 to return all unconfirmed transactions in UnconfirmedTxs RPC

- config/config.go
- config/toml.go
Closes https://github.com/celestiaorg/celestia-core/issues/1720
Used this in celestia-app
```
./scripts/single-node.sh
cat ~/.celestia-app/config/config.toml
``` 
```
#
#
indexer = "null"
```
> docs: fix default indexer in config.toml

- .github/workflows/buf-ci.yml
- .github/workflows/buf-release.yml
- buf.work.yaml
- buf.yaml
- go.mod
- go.sum
- proto/buf.yaml
Adds support to pushing proto definitions to BSR when releasing. 
This will be helpful to import RowProof, ShareProof, etc from downstream repos without redefining them.
I guess we can keep pushing our protos to BSR even if we decide to move these definitions to go-square
> chore(ci): add support for pushing proto definitions to Buf Schema Registry

- consensus/propagation/have_wants.go
Fixes a nil pointer that can happen if the compact block is nil
> chore: return if compact block is nil in handle have

- .golangci.yml
- consensus/propagation/catchup_test.go
- consensus/propagation/commitment_state.go
- consensus/propagation/have_want_test.go
- consensus/propagation/have_wants.go
- consensus/propagation/peer_state.go
- consensus/propagation/peer_state_test.go
- consensus/propagation/reactor.go
- consensus/propagation/reactor_test.go
- consensus/propagation/types/types.go
> feat: limit per peer per block concurrent requests

- consensus/propagation/catchup.go
- consensus/propagation/catchup_test.go
@rach-id found that removing the current height fixed the issues we were seeing in the e2e test. Intuitively, this fix makes sense since we started verifying the proposal we won't increment the current height, which means we wouldn't retry. I'm not sure how it was working before tbh.
> fix: increment the current height when adding a commitment

- .github/dependabot.yml
Closes https://github.com/celestiaorg/celestia-core/issues/1816 by disabling dependabot on `main`.
After this, we should only get PRs for Github actions dependencies but also open to disabling those and bumping them only when we pull upstream.
> ci: disable dependabot for `main`

- go.mod
- go.sum
- scripts/mockery_generate.sh
- test/docker/Dockerfile
- test/e2e/docker/Dockerfile
Bump go version to 1.24.0 to fix govuln CI in v0.38.x-celestia: https://github.com/celestiaorg/celestia-core/actions/runs/15562910160/job/43819564223?pr=1955
Closes #1983
> chore: update Go version to 1.24

- DOCKER/Dockerfile
- README.md
- go.mod
Fixes CI in https://github.com/celestiaorg/celestia-core/actions/runs/15675634512/job/44155160210
> chore: bump dockerfile go version to 1.24

- .github/copilot-setup-steps.yml
Updates all instances of actions/cache@v3 to actions/cache@v4
Changes:
- Updates all instances of actions/cache@v3 to actions/cache@v4
Reference:
Latest version confirmation: https://github.com/actions/cache/releases/tag/v4.2.3
This update ensures we're using the most recent stable version of the GitHub cache action across our CI/CD pipelines, with improved security features like masking of SAS tokens in debug logs.
> Update actions/cache to v4.2.3

- blocksync/reactor.go
- consensus/byzantine_test.go
- consensus/propagation/reactor.go
- consensus/propagation/reactor_test.go
- consensus/reactor.go
- consensus/reactor_test.go
- docs/celestia-architecture/adr-010-reactor-specific-peers.md
- evidence/reactor.go
- evidence/reactor_test.go
- mempool/cat/reactor_test.go
- mempool/nop_mempool.go
- mempool/priority/reactor.go
- mempool/priority/reactor_test.go
- mempool/reactor.go
- mempool/reactor_test.go
- p2p/base_reactor.go
- p2p/mock/reactor.go
- p2p/pex/pex_reactor.go
- p2p/pex/pex_reactor_test.go
- p2p/switch.go
- p2p/switch_test.go
- statesync/reactor.go
This PR introduces reactor-specific peer management to the P2P switch, enabling different reactors to maintain their own peer sets rather than sharing a single global peer set. While the infrastructure is now in place for selective peer management, all peer sets are currently identical as most reactors accept all peers.
Almost all peer sets are currently identical because:
- Most reactors (consensus, blocksync, evidence, statesync, mempool, pex) return nil from AddPeer(), accepting all peers
- Only the consensus propagation reactor rejects self-peers and duplicate peers
Testing
- The test reactor demonstrates the concept with a configurable peerLimit
- Per-reactor broadcasting is thoroughly tested
This PR provides the foundation for more sophisticated peer management while maintaining …
> feat: Reactor Specific Peers

- consensus/reactor.go
the node operator shouldn't need to do anything here and this log occurs every single time they try to send them a block part... so seems like a bad thing to error on.
to clarify further this log only gets hit when a peer is catching up from a block height the host doesn't have due to pruning or syncing.
> chore: change "Failed to load block meta" catchup log to debug

- p2p/pex/pex_reactor.go
- p2p/pex/pex_reactor_test.go
The PEX (Peer Exchange) reactor was causing frequent blacklisting of legitimate nodes due to overly strict timing requirements. From the logs:
```
peer (05ab6aa55a2cedadde73506b14cdf90ea2164986) sent next PEX request too soon.
lastReceived: 2025-07-04 10:55:27.652801791 +0000 UTC,
now: 2025-07-04 10:55:37.554963683 +0000 UTC,
minInterval: 10s. Disconnecting
```
The time difference was 9.902 seconds, which was less than the 10-second minimum interval, causing the peer to be disconnected and blacklisted.
The implementation didn't match the specification in two key areas:
1. **`defaultEnsurePeersPeriod`** was set to 10 seconds instead of 30 seconds as specified
2. **`minReceiveRequestInterval()`** was returning the full `ensurePeersPeriod` instead of `ensurePeersPeriod / 3`
According to the …
> fix: adjust PEX request interval to match specification (backport #2140)

- .github/mergify.yml
Mergify hasn't been backporting any PRs to v0.38.x-celestia. The import issue is that the labels in the config didn't match the labels on the repo.
While I was here, I removed the merge queue which we don't use, some unnecessary conditions, a backport section for v0.37.x which we don't maintain
Reviewers should verify the labels in this PR match the labels on the repo at https://github.com/celestiaorg/celestia-core/labels?q=backport
> fix(ci): backport rules

- abci/types/types.go
- abci/types/types_test.go
makes json decoding the v0.34 proto messages backwards compatible with the new ones.
the main issue is that while the data over the wire is the same for bytes and strings in protobuf, the marhalling and unmarshalling of json is not the same.
The fix here is to decode and encode in a backwards compatible way.
> fix: make json decoding old v0.34 EventAttribute backwards compatible

- rpc/core/env.go
- rpc/core/env_test.go
- rpc/core/mempool.go
- rpc/core/mempool_test.go
Part of https://github.com/celestiaorg/celestia-app/issues/5279
https://github.com/celestiaorg/celestia-core/pull/1949 contained a regression because a nil limitPerPage causes UnconfirmedTxs to panic.
Before that PR, the [validatePerPage](https://github.com/rootulp/celestia-core/blob/041b5177919562c111cad22c6aabac8a62de5a3a/rpc/core/env.go#L120-L123) would handle a nil limitPerPage by falling back to the default so that's what I did in this PR.
Added unit tests to cover it too.
> fix: panic due to nil limit

- consensus/common_test.go
- consensus/state.go
This PR adds support for the proposer to build the next block during the timeout commit. It allows saving ~0.5s, which is the time prepare-proposal takes, when proposing the block. So, straight after the timeout commit ends, the propose starts disseminating the block parts.
This optimization only works for first round, i.e., round 0, in the case where the mempool already has txs. The other two cases do not support this:
- For proposing the block for a round >= 1: There is no way to know if the network will reach consensus for a round `r` or not. So, building the block in this case will be meaningless unless we expect the network to frequently have multiple rounds. Also, it would add complicated logic to handle the case where the network reaches consensus for round `r` and needs to discard …
> feat: build the block pre-emptively during the commit timeout

- consensus/propagation/commitment.go
- consensus/propagation/have_wants.go
part of #2240
initializes the peer state before the proposer attempts to update the peer state for the receiving node. There's not a lot of reason to do this, since the proposer already has all the block data. That's updated as comment in this PR as well.
It's also unclear to me in the consensus peer state is getting updated, which means the redundant part could still be sent.
> fix: initialize peer state when proposing

- consensus/state.go
This error happens because we're running two gossip routines. So, naturally the propagation reactor will gossip the proposal first and will be sent to the consensus reactor. Then, the legacy gossip routine also propagates the same proposal which sometimes is outdated.
> chore: add more details to the invalid proposal error

- consensus/state.go
This only builds the block pre-emptively if the timeout commit is set to > 1s to avoid race conditions when running tests that use ~100ms timeout commit.
> chore: only build the block pre-emptively when the timeout commit is high

- consensus/propagation/reactor.go
- consensus/reactor.go
- consensus/state.go
- consensus/state_test.go
- evidence/reactor.go
- mempool/cat/reactor.go
- mempool/priority/reactor.go
- mempool/reactor.go
- p2p/conn/connection.go
This helps to avoid blocking during messages processing. Also, with these numbers, the RAM usage < 6GB, so it's fine.
> chore: increase propagation/consensus/p2p send queue sizes

- consensus/state.go
Previously, it was use an unbuffered channel which required both sender/receiver to be doing the same at the same time. This isn't always the case.
> chore: correctly initialise the new height channel

- mempool/cat/reactor.go
Closes https://github.com/celestiaorg/celestia-core/issues/2271
The underlying cause seems to be `nil` peers not cleaned up. This also happens in the propagation reactor and we still didn't get to the root of the issue. 
So, I created this PR to avoid the infinite recursions. Then, i'll open another issue to investigate the nil peer issue.
> fix: make the findNewPeerToRequestTx iterative

- consensus/state.go
blocks are built pre-emptively using the timeout commit from the config instead of what is passed back from the application.
I'm not sure, but don't think this is causing any problems currently. It could in the future though so we should change it.
> fix: use the timeout commit passed from the application to determine if

- consensus/propagation/catchup.go
- consensus/propagation/types/combined_partset.go
- consensus/replay_test.go
- consensus/state.go
- consensus/state_test.go
- node/node_test.go
- store/store.go
- store/store_test.go
- types/part_set.go
- types/part_set_test.go
Enhanced `PartSet` by utilizing a single preallocated buffer for part storage, reducing memory overhead. Updated related methods, removing part array access in favor of buffer management.
The biggest difference is in reading - because we can return entire buffer, it's 0 overhead., while previous implementation using io.ReadAll and custom Reader was way slower.
In artificial benchmarks, inserting parts into PartSet takes similar time, but some allocations are saved - hopefully this could be more significant in real world.
```
$ go test -bench BenchmarkPartSetRoundTrip -benchtime 1s
goos: linux
goarch: amd64
pkg: github.com/cometbft/cometbft/types
cpu: Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
BenchmarkPartSetRoundTrip/dataSize=1000,partSize=256/write-16   	  133821	      8993 ns/op …
```
> refactor!: replace `PartSet` parts slice with buffer

- scripts/metricsgen/metricsgen.go
- types/event_bus.go
while debugging I noticed that a value of 0 can result in the consensus reactor slowing down a lot since if this buffer gets caught it will end up holding the consensus mutexes!!
come to find out the default buffer is 0...
iirc, I remember changing this for the first mamo as well although i'm not sure it if fixed or changed anything
> fix: increase event bus buffer

- config/config.go
- consensus/state.go
Couple chores that improve the docs and make that log debug level so it's not noisy.
> chore: update DelayedPrecommitTimeout docs and make its log debug level

- consensus/nil_vote_test.go
- consensus/propagation/have_wants.go
- p2p/base_reactor.go
- p2p/base_reactor_test.go
this stops some panics from occurring since the new queues were added on main.
I might have gone a bit overboard with the tests but given the importance here I think its worth it.
The only reason for the ! is that I cleaned up a function that returned an error when it didn't need to, and the only way to handle that error was to panic
> fix!: stop panics in parallel reactor processing

- consensus/state.go
- types/utils.go
saves the proposals to data/debug for v0.38 (v5) to help debug
> feat: store proposals with invalid signatures to the data/debug

- test/e2e/node/config.go
- test/e2e/node/main.go
> fix: replace string literals with constants in test/e2e/node to resolve goconst linter error

- consensus/reactor_test.go
- types/params.go
`MaxBlockSizeBytes` was set to very strange value, this PR changes it to 128 MiB (and makes this more explicit).
> fix: set MaxBlockSizeBytes to 128MiB

- mempool/cat/reactor.go
One thing that I noticed during our recent traces was that often the original node operator was uploading the new transactions too much, which ended up slowing distribution.
We can reduce this and try to force the higher throughput case by doing the same thing we do when we normally broadcast a seenTx, which is to limit the number of peers that we send them to.
Here's a trace of the problematic case, where under congestion the broadcaster is uploading the transaction too much
We want more cases that look like this trace, where we  peers of the broadcaster are doing a lot of work.
for posterity, I'll also link the 
[graph.py](https://github.com/user-attachments/files/22649363/graph.py)
python script to generate these traces here.
> fix: limit the number of SeenTx broadcast for new txs
