celestiaorg/celestia-core

.github/workflows/lint.yaml
CHANGELOG.md
CHANGELOG_PENDING.md
blockchain/v2/reactor_test.go
config/config.go
docs/package-lock.json
docs/package.json
evidence/errors.go
evidence/pool.go
evidence/pool_test.go
evidence/reactor.go
evidence/store.go
evidence/store_test.go
lite2/client.go
lite2/provider/http/http.go
lite2/provider/http/http_test.go
mempool/reactor.go
mempool/reactor_test.go
node/node.go
p2p/pex/errors.go
p2p/pex/pex_reactor.go
p2p/pex/pex_reactor_test.go
p2p/transport.go
p2p/transport_test.go
rpc/core/evidence.go
state/execution.go
state/store_test.go
types/validator_set.go
types/validator_set_test.go
version/version.go

Update to latest tendermint/master

---

README.md

Closes: #XXX
______
For contributor use:

Resize banner in Readme

---

.github/workflows/e2e-nightly.yml

Notifications in the main channel started to be annoying

Separate channel for nightly e2e test

---

p2p/ipld/plugin/go.mod

Fix the ipld-plugin module name

---

README.md

Update readme's Go version badge to accurately reflect the repo's.

Update readme Go version badge.

---

abci/types/types.pb.go
proto/tendermint/blockchain/types.pb.go
proto/tendermint/consensus/types.pb.go
proto/tendermint/consensus/wal.pb.go
proto/tendermint/crypto/keys.pb.go
proto/tendermint/crypto/proof.pb.go
proto/tendermint/libs/bits/types.pb.go
proto/tendermint/mempool/types.pb.go
proto/tendermint/p2p/conn.pb.go
proto/tendermint/p2p/pex.pb.go
proto/tendermint/p2p/types.pb.go
proto/tendermint/privval/types.pb.go
proto/tendermint/state/types.pb.go
proto/tendermint/statesync/types.pb.go
proto/tendermint/store/types.pb.go
proto/tendermint/types/block.pb.go
proto/tendermint/types/canonical.pb.go
proto/tendermint/types/events.pb.go
proto/tendermint/types/params.pb.go
proto/tendermint/types/types.pb.go
proto/tendermint/types/validator.pb.go
proto/tendermint/version/types.pb.go
rpc/grpc/types.pb.go

regenerate proto messages with gogoproto 1.32
Closes: #XXX

regenerate proto messages

---

p2p/ipld/read_test.go

Quick fix. Looks like we can close https://github.com/lazyledger/rsmt2d/issues/21
@evan-forbes feel free to close this if you prefer to include the fix in #261.

Fix extended width glitch in test 

---

go.mod
go.sum
ipfs/plugin/nmt.go
ipfs/plugin/nmt_test.go
p2p/ipld/read_test.go
p2p/ipld/wrapper/nmt_wrapper.go
p2p/ipld/wrapper/nmt_wrapper_test.go

see: lazyledger/nmt#37, lazyledger/nmt#38 and https://github.com/lazyledger/lazyledger-core/issues/330#issuecomment-846289004

update to nmt v0.5.0

---

docs/lazy-adr/adr-001-block-propagation.md

Fix broken link to https://github.com/lazyledger/lazyledger-core/blob/master/docs/lazy-adr/assets/user-request.png

quickfix: broken link in adr001

---

docs/lazy-adr/README.md

rendered https://github.com/lazyledger/lazyledger-core/blob/f511569a51bfb2d478416ae1d6f53a83f3c1b51f/docs/lazy-adr/README.md

Quickfix: Update Readme to include all ADRs

---

.github/CODEOWNERS

quickfix: Update CODEOWNERS to represent actual workflow

---

docs/adr/adr-005-decouple-blockid-and-partsetheader.md

move adr 005 into correct directory

fix hickup introduced due to rebranding

---

go.mod
go.sum
pkg/consts/consts.go

use celestia specific consts, along with using the latest version of nmt
Closes: #XXX

add celestia specific consts

---

README.md

just some changes to the readme file with social links and careers section.

update with social links and careers section

---

.github/workflows/pending-changelog-checker.yml
CELESTIA_CHANGELOG.md

Create GH action to ensure that `CHANGELOG_PENDING.md` is updated on all commits to `master`
Closes: #588

Create changelog checker GH action

---

.github/CODEOWNERS

Remove @musalbas from CODEOWNERS

---

CHANGELOG.md

forgot to add all the changes to the change log

add changes to change log for v0.34.15-celestia

---

.github/CODEOWNERS
.github/dependabot.yml

Fix codeowners

---

crypto/xchacha20poly1305/xchachapoly_test.go

fix the wrapping directive error currently in a few of the tests

fix the wrapping directive causing some tests to fail

---

.github/workflows/coverage.yml
.github/workflows/docker.yml
.github/workflows/e2e.yml
.github/workflows/lint.yaml
.github/workflows/linter.yml
.github/workflows/proto-docker.yml
.github/workflows/tests.yml

Change CI to work on pushes to default branch instead of master.

---

Makefile

Remove check rule from makefile.

---

Makefile

Fixes https://github.com/celestiaorg/celestia-core/runs/6003649967?check_suite_focus=true

Fix proto breakage URL.

---

rpc/core/events.go

bug:  temporary fix until we update to tendermint 0.35

---

.github/workflows/coverage.yml
.github/workflows/e2e-nightly-34x.yml
.github/workflows/e2e-nightly-master.yml
.github/workflows/e2e.yml
.github/workflows/fuzz-nightly.yml
.github/workflows/release.yml
.github/workflows/tests.yml
DOCKER/Dockerfile
Makefile
go.mod
go.sum
test/docker/Dockerfile
test/e2e/docker/Dockerfile

update rsmt2d 03.1 -> 0.4.0

---

README.md

Please add a description of the changes that this PR introduces and the files that
are the most critical to review.
If this PR fixes an open Issue, please include "Closes #XXX" (where "XXX" is the Issue number) 
so that GitHub will automatically close the Issue when this PR is merged.

Update careers link

---

docs/celestia-architecture/adr-007-minimal-changes-to-tendermint.md

See https://github.com/celestiaorg/celestia-core/blob/v0.35.x-celestia/docs/celestia-architecture/img/core-node-relation.jpg

Fix image file extension

---

docs/celestia-architecture/README.md

Supersedes https://github.com/celestiaorg/celestia-core/pull/795

fix: links on celestia-architecture README

---

docs/celestia-architecture/adr-001-block-propagation.md
docs/celestia-architecture/adr-002-ipld-da-sampling.md
docs/celestia-architecture/adr-003-application-data-retrieval.md
pkg/consts/consts.go
pkg/da/data_availability_header.go
proto/tendermint/da/data_availability_header.pb.go
proto/tendermint/da/data_availability_header.proto

Fixes the specs links across the repo.
Closes https://github.com/celestiaorg/celestia-core/issues/805

fix specs links

---

.golangci.yml

Closes https://github.com/celestiaorg/celestia-core/issues/828

Fix golangci config

---

README.md

Motivated by the steps in https://github.com/celestiaorg/celestia-core/pull/855

Add more detailed contributing steps

---

pkg/consts/consts.go
rpc/core/tx.go

Use a custom ABCI Query
Closes: #851

feat!: Use a custom ABCI query to prove transaction inclusion

---

pkg/consts/consts.go

Closes https://github.com/celestiaorg/celestia-core/issues/841
Opens https://github.com/celestiaorg/celestia-app/pull/709

breaking!: move share consts to celestia-app

---

.github/CODEOWNERS

Closes https://github.com/celestiaorg/celestia-core/issues/857

Remove @liamsi from global CODEOWNERS

---

rpc/core/tx.go

docs: update the tx link and remove unnecessary comment.

---

crypto/merkle/proof_op.go
crypto/merkle/proof_test.go

chore!: add docs and tests to new VerifyFromKeys methods

---

rpc/client/rpc_test.go
rpc/core/tx.go

Throws an error when attempting to prove tx inclusion
Closes: #918

chore: throw and error when attempting to prove tx inclusion

---

light/proxy/routes.go
light/rpc/client.go
rpc/client/http/http.go
rpc/client/interface.go
rpc/client/local/local.go
rpc/client/mock/client.go
rpc/core/blocks.go
rpc/core/routes.go

- Rename Data Commitment arguments to first/last block
Closes: #928

chore: rename Data Commitment arguments to first/last block

---

node/node.go

Small change to avoid large swaths of lost time in the future

fix: run validate basic on config in node constructor

---

go.mod
go.sum

Downgrade to nmt 0.12.0 until https://github.com/celestiaorg/celestia-node/pull/1651 is resolved

chore: downgrade to nmt 0.12.0

---

.github/workflows/check-generated.yml
Makefile

Attempt to fix https://github.com/celestiaorg/celestia-core/issues/973
Inspired by: 
1. https://github.com/cometbft/cometbft/blob/754f1ae9e29a84754aa42ac969f0cd369266f019/.github/workflows/check-generated.yml#L52-L66
2. https://github.com/cometbft/cometbft/blob/754f1ae9e29a84754aa42ac969f0cd369266f019/Makefile#L127-L132

ci: fix proto-gen failing workflow

---

mempool/cat/pool_test.go
mempool/v0/clist_mempool_test.go
mempool/v1/mempool_test.go
pkg/consts/consts.go
types/tx.go
types/tx_test.go

Part of https://github.com/celestiaorg/celestia-app/issues/1444
Verified the length in https://go.dev/play/p/xwza9bDcfdf

feat!: increase tx namespace id to 32 bytes

---

types/block.go

Closes https://github.com/celestiaorg/celestia-core/issues/982

chore!: remove `BlobFromProto` and `BlobsFromProto`

---

.github/CODEOWNERS

I am not anymore :sob:
For a looong time. Feels like decades ❤️

fix(.github): update CODEOWNERS

---

rpc/core/blocks.go

be advised that it may take some time before it is merged - especially if it has
not yet been discussed with the …

docs: document data root tuple hex representation padding

---

Makefile

Remove `check` dependency for `all` from Makefile.

---

Makefile

Re-do #1010 which was reverted by accident in #1021 by @evan-forbes.
---

Remove `check` dependency for `all` from Makefile. Again.

---

abci/types/types.pb.go
proto/tendermint/abci/types.proto

Closes https://github.com/celestiaorg/celestia-core/issues/1029

docs: fix godoc for chain_id

---

pkg/trace/client.go

since its difficult to test the tracer irl, we missed this silly bug :facepalm:

fix: pass configured tables to the trace client

---

go.mod
go.sum

https://github.com/celestiaorg/celestia-core/pull/1073#issuecomment-1706603291

build(deps): bump nmt to 0.19.0

---

.github/mergify.yml

adds mergify rule to backport PRs to v0.34.x-celestia

chore: add backport rule to mergify

---

docs/celestia-architecture/README.md
docs/celestia-architecture/adr-009-cat-pool.md

Somehow I forgot to add this ADR to the repo documenting the design and testing of the CAT pool

docs: add adr on cat pool

---

.github/workflows/govulncheck.yml

Closes https://github.com/celestiaorg/celestia-core/issues/1023

ci: enable govulncheck

---

README.md

Based on a discussion in sprint meeting. Please LMK if this doesn't help, can close instead of merging.

docs: clarify intended purpose of branches

---

config/config.go
config/toml.go
mempool/cat/reactor.go
node/node.go
test/maverick/node/node.go

Closes: #1120
This is an additive change and is thus non-breaking.

feat: add MaxGossipDelay from CAT pool to the config

---

.github/CODEOWNERS

Closes https://github.com/celestiaorg/celestia-core/issues/1211

chore: add more CODEOWNERS

---

docs/qa/CometBFT-QA-34.md

Fixed minor spelling mistakes.

chore: typo fixes

---

crypto/ed25519/ed25519.go
docs/celestia-architecture/adr-007-minimal-changes-to-tendermint.md
p2p/trust/store.go
test/maverick/consensus/state.go

chore: remove repetitive words

---

cmd/cometbft/commands/run_node.go
config/config.go
config/toml.go
go.mod
go.sum
pkg/trace/README.md
pkg/trace/decoder.go
pkg/trace/fileserver.go
pkg/trace/flags.go
pkg/trace/local_client.go
pkg/trace/local_client_test.go
pkg/trace/local_tracer.go
pkg/trace/local_tracer_test.go
pkg/trace/tracer.go
test/e2e/node/main.go
test/e2e/pkg/infrastructure.go
test/e2e/pkg/testnet.go
test/e2e/runner/main.go
test/e2e/runner/setup.go

Adds the pull based portion of the file server along with a simple client.

feat: add the pull based fileserver

---

config/toml.go
pkg/trace/fileserver.go
pkg/trace/schema/mempool.go

quick follow up for the last tracing PR

fix: follow up with doc fixes and config path creation

---

README.md

Closes https://github.com/celestiaorg/celestia-core/issues/1297

docs(README): remove broken links

---

pkg/trace/README.md
pkg/trace/local_tracer.go
pkg/trace/local_tracer_test.go

Manual backport of https://github.com/celestiaorg/celestia-core/pull/1318

feat: adds the feature to read push config from env vars (backport #1318)

---

pkg/trace/README.md
pkg/trace/local_tracer.go
pkg/trace/local_tracer_test.go

feat: adds the feature to read push config from env vars

---

rpc/core/blocks.go

Error 404:
https://docs.tendermint.com/master/rpc/#/Info/header
https://docs.tendermint.com/master/rpc/#/Info/header_by_hash
Fix:
https://docs.tendermint.com/main/rpc/#/Info/header
https://docs.tendermint.com/main/rpc/#/Info/header_by_hash
are the most critical to review._
can be reached via GitHub Discussions:
https://github.com/celestiaorg/celestia-core/discussions
be advised that it may take some …

Fix: Update Tendermint RPC Broken Link

---

rpc/openapi/openapi.yaml

Closes https://github.com/celestiaorg/celestia-core/issues/1329

docs: update the openapi specs to contain the share proof

---

.github/workflows/check-generated.yml
.github/workflows/coverage.yml
.github/workflows/e2e-manual.yml
.github/workflows/e2e-nightly-34x.yml
.github/workflows/e2e.yml
.github/workflows/fuzz-nightly.yml
.github/workflows/govulncheck.yml
.github/workflows/pre-release.yml
.github/workflows/release-version.yml
.github/workflows/release.yml
.github/workflows/tests.yml
DOCKER/Dockerfile
README.md
go.mod
scripts/proto-gen.sh
test/docker/Dockerfile
test/e2e/docker/Dockerfile

chore(deps): bump go to v1.22.3

---

light/rpc/client.go

docs: go doc feedback for PR #1351

---

state/state_test.go

chore: fix comments

---

types/row_proof.go
types/row_proof_test.go

Replica of https://github.com/celestiaorg/celestia-core/pull/1372 to main

fix: check if the end row is greater than the start row

---

types/row_proof.go
types/row_proof_test.go

Closes https://github.com/celestiaorg/celestia-core/issues/1371

fix: check if row proof end row is greater than start row

---

state/execution.go

Closes https://github.com/celestiaorg/celestia-core/issues/1391

chore: remove outdated TODO

---

.github/workflows/check-generated.yml
.github/workflows/coverage.yml
.github/workflows/e2e-manual.yml
.github/workflows/e2e-nightly-34x.yml
.github/workflows/e2e.yml
.github/workflows/fuzz-nightly.yml
.github/workflows/govulncheck.yml
.github/workflows/pre-release.yml
.github/workflows/release-version.yml
.github/workflows/release.yml
.github/workflows/tests.yml
DOCKER/Dockerfile
README.md
go.mod
scripts/proto-gen.sh
test/docker/Dockerfile
test/e2e/docker/Dockerfile

chore: upgrades go version to 1.22.5 in main

---

pkg/trace/fileserver.go

Reverts celestiaorg/celestia-core#1374

revert: enhances S3Download to filter by traced table names

---

docs/celestia-architecture/adr-001-block-propagation.md
docs/celestia-architecture/adr-002-ipld-da-sampling.md
docs/celestia-architecture/adr-003-application-data-retrieval.md

Hello
I found some spelling issues in your docs.
Glad I could help.
Br, Elias.

fix: spelling issues

---

.github/CODEOWNERS
.github/workflows/check-generated.yml
.github/workflows/coverage.yml
.github/workflows/e2e-manual.yml
.github/workflows/e2e-nightly-34x.yml
.github/workflows/e2e.yml
.github/workflows/fuzz-nightly.yml
.github/workflows/govulncheck.yml
.github/workflows/lint.yml
.github/workflows/pre-release.yml
.github/workflows/release-version.yml
.github/workflows/release.yml
.github/workflows/tests.yml
DOCKER/Dockerfile
Makefile
README.md
go.mod
scripts/proto-gen.sh
spec/p2p/reactors/mempool-v1.md
test/docker/Dockerfile
test/e2e/docker/Dockerfile

This PR ports over a few missing commits from main into v0.34.x-celestia.

chore: updates from main

---

rpc/core/tx.go

refactor: export tx status consts

---

README.md

The previous link in the documentation didn't work
be advised that it may take some time before it is merged - especially if it has
not yet been discussed with the team.
See the project board for the team's current priorities: …

docs: remove broken badge

---

behaviour/doc.go
behaviour/peer_behaviour.go
consensus/common_test.go
consensus/metrics.go
consensus/replay_file.go
statesync/syncer.go

Fix typos for logs and comments

docs: fix typos

---

consensus/propagation/peer_state.go
consensus/propagation/peer_state_test.go
consensus/propagation/types/types.go
consensus/propagation/types/types_test.go
libs/bits/bit_array.go
libs/bits/bit_array_test.go

Adds the peer state implementation and tests

feat: add the peer state implementation

---

consensus/propagation/reactor.go
consensus/propagation/reactor_test.go
consensus/propagation/types/types.go
libs/bits/bit_array.go
libs/bits/bit_array_test.go
pkg/trace/schema/consensus.go
pkg/trace/schema/schema.go

Adds the backbone of the block propagation reactor.

feat: add the backbone of the propagation logic

---

consensus/propagation/reactor.go
consensus/propagation/reactor_test.go

support for have and wants propagation and a unit test covering this

feat: support have and want propagation

---

consensus/propagation/reactor.go
consensus/propagation/reactor_test.go
types/part_set.go

add support for recovery part and test

feat: add support for recovery part

---

.github/auto_request_review.yml

cc: @ninabarbakadze @cmwaters @tzdybal

ci: update the list of default reviewers

---

.github/auto_request_review.yml

to avoid adding the others as reviewers everytime
---

chore: update the code owners in feature branch

---

consensus/propagation/catchup.go
consensus/propagation/catchup_test.go
consensus/propagation/commitment.go
consensus/propagation/commitment_state.go
consensus/propagation/commitment_test.go
consensus/propagation/have_wants.go
consensus/propagation/reactor.go
consensus/propagation/reactor_test.go
node/node.go

support catchup in the case where we didn't receive all the haves/parts from the network.
PS: doesn't cover gaps catchup.

feat: support catchup

---

consensus/propagation/catchup.go
consensus/propagation/catchup_test.go
consensus/propagation/commitment.go
consensus/propagation/commitment_state.go
consensus/propagation/commitment_test.go
consensus/propagation/have_wants.go
consensus/propagation/peer_state.go
consensus/propagation/reactor.go
consensus/propagation/reactor_test.go
node/node.go

Adds support for broadcasting haves when proposing a block

feat: broadcast haves when proposing a block

---

consensus/propagation/types/types.go

nits: cosmetics

---

abci/server/grpc_server.go

This will need to be released and added into v3 as part of the v4 upgrade. It will not effect running nodes today 

chore: increase grpc message size to allow for BIG BLONKS

---

consensus/propagation/commitment.go
consensus/propagation/reactor.go

Closes https://github.com/celestiaorg/celestia-core/issues/1705

feat: run the catchup periodically

---

consensus/propagation/commitment_state.go
node/node.go

Closes https://github.com/celestiaorg/celestia-core/issues/1717

fix: start block prop processing correctly + fix height relevance

---

config/config.go
config/toml.go

Port of https://github.com/celestiaorg/celestia-core/pull/1721 that targets v0.38.x-celestia

docs: fix default indexer in config.toml

---

state/state.go

Closes https://github.com/celestiaorg/celestia-core/issues/1767

docs: fix `InitStateVersion` docs

---

consensus/propagation/have_wants.go
consensus/propagation/have_wants_test.go
consensus/propagation/reactor_test.go
consensus/propagation/types/types.go
consensus/propagation/types/types_test.go

Closes https://github.com/celestiaorg/celestia-core/issues/1775

feat: verify haves parts hashes

---

consensus/propagation/have_want_test.go
consensus/propagation/have_wants.go

Closes https://github.com/celestiaorg/celestia-core/issues/1777

feat: dynamic limit the number of requests per part

---

consensus/propagation/types/types.go
consensus/propagation/types/types_test.go

Closes https://github.com/celestiaorg/celestia-core/issues/1716

chore: check if the tx metadata has overlapping ranges

---

consensus/propagation/commitment_state.go
consensus/propagation/have_want_test.go
consensus/propagation/have_wants.go
consensus/propagation/peer_state.go
consensus/propagation/peer_state_test.go
consensus/propagation/reactor.go

submitting a quick PR to reduce review rounds :crossed_fingers:

refactor!: fix blocking edge cases, reduce complexity, and use a design that requires zero timeouts

---

consensus/propagation/have_want_test.go
consensus/propagation/have_wants.go
consensus/propagation/reactor.go
consensus/propagation/reactor_test.go

Closes https://github.com/celestiaorg/celestia-core/issues/1776

feat: dynamic concurrent peer requests

---

consensus/propagation/types/types.go
consensus/propagation/types/types_test.go

chore: implement RecoveryPart.ValidateBasics()

---

consensus/state.go

chore: reenable process proposal

---

consensus/propagation/commitment.go
consensus/propagation/have_wants.go
consensus/propagation/types/combined_partset.go

chore: validate the recovery parts

---

consensus/propagation/catchup.go

chore: trigger catchup when receiving a commitment

---

consensus/propagation/catchup.go
consensus/propagation/commitment.go
consensus/propagation/have_wants.go
consensus/propagation/reactor.go
consensus/propagation/reactor_test.go
consensus/propagation/types/types.go

Resolves some unnecessary todos

chore: remove some dangling todos

---

consensus/propagation/commitment_state.go
consensus/propagation/have_want_test.go
consensus/propagation/have_wants.go
consensus/propagation/reactor.go

adds a conditional wait to have a proposal before starting the request from peer routine

chore: correctly start the request from peer routine

---

consensus/propagation/catchup.go

chore: use the parts request limit in catchup

---

consensus/propagation/catchup_test.go
consensus/propagation/have_wants.go

checks whether the peer exists before sending data in the channels

chore: check peer is still connected before writing to channel

---

consensus/propagation/commitment.go
consensus/state.go

chore: verifying compact block height/round

---

.github/CODEOWNERS

Closes https://github.com/celestiaorg/celestia-core/issues/1890

chore: update code owners in v0.38.x-celestia

---

consensus/propagation/have_wants.go
consensus/propagation/types/combined_partset.go

Fixes audit issue: **Unresolvable wants in PeerState**

chore: validate want parts size in handle wants

---

consensus/propagation/commitment.go

Closes: https://github.com/celestiaorg/celestia-core/issues/2066

chore: only add recovered part if it's missing

---

consensus/propagation/commitment.go
consensus/propagation/have_wants.go
consensus/propagation/peer_state.go
consensus/propagation/peer_state_test.go
consensus/propagation/reactor.go

Closes https://github.com/celestiaorg/celestia-core/issues/2065

chore: improve channels lifecycle handling

---

consensus/propagation/commitment.go

fix: validate compact block data race

---

p2p/peer.go

Replaced manual locking with atomic operations for `stopped`, `removalAttemptFailed`, and `cachedIP` fields to enhance concurrency safety. Simplified IP caching logic. Updated `FlushStop` and `OnStop` methods to be thread-safe and idempotent.
Resolves #2093

refactor: add atomic fields for thread-safe peer handling

---

README.md

Closes https://github.com/celestiaorg/celestia-core/issues/2081
Closes https://github.com/celestiaorg/celestia-core/issues/1856
Motivation https://celestia-team.slack.com/archives/C02PFFCGMNW/p1751292271120999
I copied the README from v0.34.x-celestia and then updated the sections: Branches and Releases.

docs(README): copy README from v0.34.x-celestia

---

p2p/pex/addrbook.go
p2p/pex/addrbook_test.go
p2p/pex/pex_reactor.go
p2p/pex/pex_reactor_test.go

feat: more aggressive peer discovery (backport of #2029)

---

node/node.go
state/execution.go

Adds traces for prepare proposal

chore: trace prepare proposal

---

consensus/state.go

The existing implementation wasn't tracing process proposal, it was tracing block validation

chore:trace process proposal correctly

---

README.md

Motivation: https://github.com/celestiaorg/celestia-app/issues/5147#issuecomment-3045860688

docs: explain Celestia-specific GRPC APIs

---

consensus/propagation/have_wants.go

This log also pollutes the logs

chore: make received part for unknown proposal debug level

---

mempool/cat/pool.go
mempool/cat/reactor.go
mempool/cat/reactor_test.go
mempool/priority/mempool.go
mempool/priority/mempool_test.go
mempool/priority/reactor.go
mempool/priority/reactor_test.go

fix: only purge expired txs during update

---

blocksync/reactor.go
consensus/byzantine_test.go
consensus/propagation/reactor.go
consensus/propagation/reactor_test.go
consensus/reactor.go
consensus/reactor_test.go
evidence/reactor.go
evidence/reactor_test.go
mempool/cat/reactor.go
mempool/cat/reactor_test.go
mempool/nop_mempool.go
mempool/priority/reactor.go
mempool/priority/reactor_test.go
mempool/reactor.go
mempool/reactor_test.go
p2p/base_reactor.go
p2p/mock/reactor.go
p2p/pex/pex_reactor.go
p2p/pex/pex_reactor_test.go
p2p/switch.go
p2p/switch_test.go
statesync/reactor.go

refactor: move error handling from AddPeer to InitPeer

---

consensus/propagation/commitment.go

Close: https://github.com/celestiaorg/celestia-core/issues/2248

chore: send mempool recovered parts to consensus

---

state/txindex/kv/kv.go

kept noticing this in logs and it is annoying

chore: delete println

---

mempool/cat/store.go
mempool/cat/store_test.go

fix: cat not purging txs from ordered cache

---

go.mod
go.sum

Provides an immediate performance improvement.

chore: bump nmt to v0.24.1

---

config/config.go
consensus/common_test.go
consensus/state.go
test/e2e/node/main.go
test/e2e/runner/wait.go
types/event_bus.go

Closes: https://github.com/celestiaorg/celestia-core/issues/2381#issuecomment-3229416390

feat: support delayed precommits

---

consensus/common_test.go
internal/test/tx.go
state/execution.go
state/execution_test.go
state/state.go
state/store.go
types/block.go
types/marshalling.go
types/marshalling_test.go

Closes https://github.com/celestiaorg/celestia-core/issues/2404 and https://github.com/celestiaorg/celestia-core/issues/2405
These changes give us 120ms benefit.

perf: optimse create proposal block

---

consensus/propagation/types/types.go

Please review the [CONTRIBUTING.md](../CONTRIBUTING.md) file for detailed contribution guidelines.

chore: improve error log

---

consensus/common_test.go
consensus/state_test.go

cherry picking https://github.com/celestiaorg/celestia-core/pull/2475 to see how the CI would behave with it.

chore: try fix for TestFullRound

---

.github/workflows/e2e.yml
blocksync/msgs.go
config/config.go
config/toml.go
consensus/propagation/reactor_test.go
consensus/reactor_test.go
node/node.go
node/setup.go
state/execution_test.go
test/e2e/networks/propagation-reactor-compatibility.toml
test/e2e/pkg/manifest.go
test/e2e/pkg/testnet.go
test/e2e/runner/setup.go
types/params.go

Backports https://github.com/celestiaorg/celestia-core/pull/2512 to main

feat: support a flag to enable the legacy block prop

---

p2p/pex/pex_reactor.go
p2p/pex/pex_reactor_test.go

Closes https://github.com/celestiaorg/celestia-core/issues/2525 and https://github.com/celestiaorg/celestia-core/issues/2524

feat: limit the number of addresses in pex message
